// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var draw, loadRom, setupCanvas;

  setupCanvas = function() {
    var canvas, con2d, videoBuffer;
    canvas = document.getElementById('can');
    con2d = canvas.getContext('2d');
    videoBuffer = con2d.createImageData(64, 32);
    return {
      con2d: con2d,
      videoBuffer: videoBuffer
    };
  };

  loadRom = function(romFile) {
    var promise, request;
    request = new XMLHttpRequest();
    request.open('GET', "../roms/" + romFile, true);
    request.responseType = 'arraybuffer';
    promise = new Promise(function(resolve, reject) {
      request.onload = function() {
        resolve(new Uint8Array(request.response));
      };
    });
    request.send();
    return promise;
  };

  draw = function(video, videoBuffer, con2d) {
    var i, i4, _i, _ref;
    i4 = 0;
    for (i = _i = 0, _ref = video.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
      if (video[i]) {
        videoBuffer.data[i4 + 0] = 255;
        videoBuffer.data[i4 + 1] = 255;
        videoBuffer.data[i4 + 2] = 255;
      } else {
        videoBuffer.data[i4 + 0] = 0xC;
        videoBuffer.data[i4 + 1] = 0xD;
        videoBuffer.data[i4 + 2] = 0x8;
      }
      videoBuffer.data[i4 + 3] = 255;
      i4 += 4;
    }
    con2d.putImageData(videoBuffer, 0, 0);
  };

  window.Chip8Common = {
    setupCanvas: setupCanvas,
    loadRom: loadRom,
    draw: draw
  };

}).call(this);
