// Generated by CoffeeScript 1.11.0
(function() {
  'use strict';
  var Chip8Keyboard;

  Chip8Keyboard = function() {
    var getHtml, getState, layout, setEventListener, state, waitCallback, waitForKey;
    layout = [['1', '2', '3', 'C'], ['4', '5', '6', 'D'], ['7', '8', '9', 'E'], ['A', '0', 'B', 'F']];
    state = new Uint8Array(16);
    getState = function(key) {
      return state[key];
    };
    waitCallback = null;
    waitForKey = function(callback) {
      return waitCallback = callback;
    };
    setEventListener = function(button, key) {
      button.addEventListener('mouseup', function() {
        state[key] = 0;
      });
      button.addEventListener('mousedown', function() {
        state[key] = 1;
        if (waitCallback != null) {
          waitCallback(key);
          waitCallback = null;
        }
      });
    };
    getHtml = function() {
      var table;
      table = document.createElement('table');
      table.classList.add('keyboard');
      layout.forEach(function(line) {
        var tr;
        tr = document.createElement('tr');
        table.appendChild(tr);
        return line.forEach(function(key) {
          var button, td;
          td = document.createElement('td');
          tr.appendChild(td);
          button = document.createElement('button');
          button.textContent = key;
          button.classList.add('key');
          td.appendChild(button);
          setEventListener(button, parseInt(key, 16));
        });
      });
      return table;
    };
    return {
      getHtml: getHtml,
      getState: getState,
      waitForKey: waitForKey
    };
  };

  window.Chip8Keyboard = Chip8Keyboard;

}).call(this);
