// Generated by CoffeeScript 1.8.0
(function() {
  'use strict';
  var app;

  app = angular.module('Chip8', []);

  app.controller('Chip8Controller', [
    '$scope', '$http', function($scope, $http) {
      var draw, initContext, setVideoData, _ref;
      _ref = Chip8Renderer(), initContext = _ref.initContext, draw = _ref.draw, setVideoData = _ref.setVideoData;
      this.selectedRomName = 'MAZE';
      this.romNames = ['15PUZZLE', 'BLINKY', 'BLITZ', 'BRIX', 'CONNECT4', 'GUESS', 'HIDDEN', 'INVADERS', 'KALEID', 'MAZE', 'MERLIN', 'MISSILE', 'PONG', 'PONG2', 'PUZZLE', 'SYZYGY', 'TANK', 'TETRIS', 'TICTAC', 'UFO', 'VBRIX', 'VERS', 'WIPEOFF', 'ZERO'];
      this.changeRom = function() {
        return ($http.get("../roms/" + this.selectedRomName, {
          responseType: 'arraybuffer'
        })).success((function(_this) {
          return function(data) {
            _this.chip8.load(new Uint8Array(data));
            return _this.chip8.reset();
          };
        })(this));
      };
      this.init = function() {
        var keyboard;
        initContext(document.getElementById('can'));
        keyboard = Chip8Keyboard();
        (document.getElementById('container')).appendChild(keyboard.getHtml());
        this.chip8 = Chip8();
        return this.chip8.setKeyboard(keyboard);
      };
      this.init();
      return this.changeRom().then((function(_this) {
        return function() {
          var TICKS_PER_FRAME, mainLoop;
          TICKS_PER_FRAME = 10;
          mainLoop = function() {
            var i, _i;
            for (i = _i = 0; 0 <= TICKS_PER_FRAME ? _i < TICKS_PER_FRAME : _i > TICKS_PER_FRAME; i = 0 <= TICKS_PER_FRAME ? ++_i : --_i) {
              _this.chip8.tick();
            }
            setVideoData(_this.chip8.getVideo());
            draw();
            requestAnimationFrame(mainLoop);
          };
          mainLoop();
        };
      })(this));
    }
  ]);

}).call(this);
